# Generated by Django 2.2.6 on 2020-10-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='caption',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(default='', upload_to='../upload_test'),
        ),
    ]
