# Generated by Django 2.2.6 on 2020-10-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20201023_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='../upload_test'),
        ),
    ]
